[model]
name = "ImageClassifier"
version = "1.0"

[model.parameters]
learning_rate = 0.001
batch_size = 64
num_epochs = 10

[model.layers]
type = ["conv", "pool", "dense"]
num_units = [32, 64, 128]

[constants]
const_decl = "0.001 -> lr"
const_eval = "|lr| = learning_rate"
